// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq27Y8t9FlPmvF2hsSFWy4cUwfZXCVlaQ',
    appId: '1:1083771712062:web:95daa1daa16ef154cc576f',
    messagingSenderId: '1083771712062',
    projectId: 'api-project-1083771712062',
    authDomain: 'api-project-1083771712062.firebaseapp.com',
    databaseURL: 'https://api-project-1083771712062.firebaseio.com',
    storageBucket: 'api-project-1083771712062.appspot.com',
    measurementId: 'G-WVKPPMM06Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnLQO1FH7xfqHKCOKvgGelBqsEBlW1v6w',
    appId: '1:1083771712062:android:e205d61be88813b8cc576f',
    messagingSenderId: '1083771712062',
    projectId: 'api-project-1083771712062',
    databaseURL: 'https://api-project-1083771712062.firebaseio.com',
    storageBucket: 'api-project-1083771712062.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTSCAPYSVlQMf0CZ-ryL9lzve3HMGPocs',
    appId: '1:1083771712062:ios:d860febbdc51d24fcc576f',
    messagingSenderId: '1083771712062',
    projectId: 'api-project-1083771712062',
    databaseURL: 'https://api-project-1083771712062.firebaseio.com',
    storageBucket: 'api-project-1083771712062.appspot.com',
    iosClientId: '1083771712062-270oe6i5lvochmv8cvqvs1pm1u6s0b9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.tennisCashCourt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTSCAPYSVlQMf0CZ-ryL9lzve3HMGPocs',
    appId: '1:1083771712062:ios:d860febbdc51d24fcc576f',
    messagingSenderId: '1083771712062',
    projectId: 'api-project-1083771712062',
    databaseURL: 'https://api-project-1083771712062.firebaseio.com',
    storageBucket: 'api-project-1083771712062.appspot.com',
    iosClientId: '1083771712062-270oe6i5lvochmv8cvqvs1pm1u6s0b9s.apps.googleusercontent.com',
    iosBundleId: 'com.example.tennisCashCourt',
  );
}
