import 'package:get/route_manager.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'cs_Cz': {
          'hello': 'Ahoj',
          'nameApp': 'Počítání tenisových hodin',
          'search': 'Hledej',
          'fromDate': 'Od data: ',
          'toDate': 'Do data: ',
          'totalHours': 'Celkem hodin: ',
          'hours': ' hodin',
          'totalPrice': 'Celková cena: ',
          'nothingToPay': 'Nic k zaplacení!',
          'paymentAllHours': 'Zaplať',
          'currentPlayer': 'Aktuální hráč:',
          'namePlayer': 'Jméno hráče',
          'password': 'Heslo',
          'isAdmin': 'Je administrátor',
          'common': 'Obecné nastavení:',
          'hourPrice': 'Cena za hodinu',
          'currency': 'Měna',
          'language': 'Jazyk',
          'ok': 'Ok',
          'cancel': 'Zrušit',
          'enterNewPass': 'Vlož nové heslo',
          'enterNamePlayer': 'Vlož jméno hráče',
          'enterShortCurrency': 'Vlož zkrácený název měny',
          'enterHourPrice': 'Vlož cenu za hodinu',
          'addNewName': '..přidat nové jméno',
          'partner': 'Spoluhráč: ',
          'edit': 'Upravit',
          'delete': 'Vymazat',
          'addNewHour': 'Přidat další hordinu',
          'payTennisHours': 'Zaplacení',
          'payTennisQuestion': 'Chcete všechny hodiny zaplatit? Cena je: ',
          'current': 'Zadej',
          'filter': 'Vyhledávání',
          'pay': 'Placení',
          'synchronization': 'Synchronizace',
          'settings': 'Nastavení',
          'addNewTennisCourse': 'Přidat novou hodinu',
          'sameNamePartners': 'Jména dvou spoluhráčů se shodují',
          'hours:': 'Hodin: ',
          'addPartner': 'Přidat dalšího spoluhráče',
          'selectHours': 'Prosím vyberte počet hodin',
          'date': 'Datum: ',
          'newNamePartner': 'Nové jméno spoluhráče',
          'newName': 'Nové jméno',
          'thisName': 'Zadané jméno ',
          'exists': ' již existuje',
          'questDelete': 'Chcete vymazat všechny data?'
        },
        'en_US': {
          'hello': 'Hello',
          'nameApp': 'Counting tennis hours',
          'search': 'Search',
          'fromDate': 'From date: ',
          'toDate': 'To date: ',
          'totalHours': 'Total hours: ',
          'hours': ' hours',
          'totalPrice': 'Total price: ',
          'nothingToPay': 'Nothing to pay!',
          'paymentAllHours': 'Pay',
          'currentPlayer': 'Current player:',
          'namePlayer': 'Player name',
          'password': 'Password',
          'isAdmin': 'Is administrator',
          'common': 'Common settings:',
          'hourPrice': 'Price per hour',
          'currency': 'Currency',
          'language': 'Language',
          'ok': 'Ok',
          'cancel': 'Cancel',
          'enterNewPass': 'Enter new password',
          'enterNamePlayer': 'Enter player name',
          'enterShortCurrency': 'Enter short code currency',
          'enterHourPrice': 'Enter price per hour',
          'addNewName': '..Add new name',
          'partner': 'Playmate: ',
          'edit': 'Edit',
          'delete': 'Delete',
          'addNewHour': 'Add new hour',
          'payTennisHours': 'Pay',
          'payTennisQuestion': 'Do you want to pay all hours? Price is: ',
          'current': 'Add',
          'filter': 'Filter',
          'pay': 'Pay',
          'synchronization': 'Synchronization',
          'settings': 'Settings',
          'addNewTennisCourse': 'Add new tennis lesson',
          'sameNamePartners': 'There is same name playmates',
          'hours:': 'Hours: ',
          'addPartner': 'Add new playmate',
          'selectHours': 'Please, select hour',
          'date': 'Date: ',
          'newNamePartner': 'New name playmates',
          'newName': 'New name',
          'thisName': 'This name ',
          'exists': ' have existed',
          'questDelete': 'Do you want delete all data?'
        },
      };
}
